### ISSUE TITLE
Validation::notEmpty() is deplecated in CakePHP 2.7.

### ISSUE THREAD

**Issue by okinaka** [CakeDC/tags#101]
Because Tag model is using 'notEmpty' validation, Unit testing is failed in CakePHP 2.7.

https://github.com/CakeDC/tags/blob/master/Model/Tag.php#L45-L48

**Comment by steinkel** [comment]
hi @okinaka I would keep BC in the tags plugin to CakePHP versions below 2.7 too, using a custom validation rule instead

**Comment by okinaka** [comment]
@steinkel Ok, I will try to create custom validation rule. What name shall I make it?

**Comment by okinaka** [comment]
Fixed #102 for custom validation.

**Comment by steinkel** [comment]
This should be fixed now in release 1.6.1
