### ISSUE TITLE
Non possible to instal on cake 3.1 and also not possilbe on 3.0

### ISSUE THREAD

**Issue by ironbone** [CakeDC/tags#103]
After running 
composer require cakedc/tags
With cake 3.1
I get the following error.

It seams the this is beacause the missing
"autoload": 
section in your composer.json

----------------------------------------------------------
.....
Generating autoload files
> Cake\Composer\Installer\PluginInstaller::postAutoloadDump
Script Cake\Composer\Installer\PluginInstaller::postAutoloadDump handling the post-autoload-dump event terminated with an exception

                                                                               
  [RuntimeException]                                                           
  Unable to get primary namespace for package cakedc/tags.                     
  Ensure you have added proper 'autoload' section to your plugin's config as   
  stated in README on https://github.com/cakephp/plugin-installer

**Comment by ironbone** [comment]
I have just testet with a fresch cake 3.0.5 application. I get the same error.

**Comment by steinkel** [comment]
Hi @ironbone this plugin is for CakePHP 2.5+ we are work in progress 3.x migration under branch 3.0, but not released yet for 3.x.

Thank you.
