### ISSUE TITLE
Manage tags

### ISSUE THREAD

**Issue by YuzuruS** [CakeDC/tags#107]
Hi. this plugin include "Manage tags".
I don't want to use this function.
How do I do?

**Comment by andrej-griniuk** [comment]
Hi YuzuruS,
you could, for instance, overwrite `/tags/*` route in your `routes.php` with something, e.g.:

> Router::redirect('/tags/*', '/');

Hope this helps.

**Comment by Megslalk** [comment]
This issue will be closed; Please feel free to re-open or create a new issue if you still need assistance. Thanks!
