### ISSUE TITLE
Tags with special chars cause double assignments, they're seen as the same

### ISSUE THREAD

**Issue by burzum** [CakeDC/tags#109]
For whatever reason we had two "berlin" tags in our DB. One was with a regular `I` and one with `Í`. The funny thing that now happened was that an user entered "berlin" but afterwards the article was associated with both berlins, the `berlin` and the `berlín`. The plugins seems to not make a difference between them when looking up the tags and associate them with the article.

This will probably cause more issues for Spanish speaking people. In your case it was more like an accident that we had a second berlin with `´` but I'm pretty sure there are languages where the same word with just a different ` or ´ are common.

We're using the cake2 version in this project.

**Comment by andre-pdassis** [comment]
Maybe this happened due some kind of string treatment that standardize the tag name to be associated.

**Comment by burzum** [comment]
Feel free to close it. I don't even know if this is an issue in our app anymore. For Cake3 we've switched to https://github.com/usemuffin/tags

**Comment by Megslalk** [comment]
Closing issue - Please re-open if necessary!
