### ISSUE TITLE
Cannot load schema

### ISSUE THREAD

**Issue by MarChar** [CakeDC/tags#112]
Hi,
Im facing the bellow issue when running the command.. Does anyone knows why?

cake Schema create schema --plugin Tags --name Schema

The chosen schema could not be loaded. Attempted to load:
File: C:\xampp\htdocs\shop\app\Plugin\Tags\Config\Schema\schema.php
Name: Schema

The above file exists in that location

---

class Schema extends CakeSchema {

---

Thank you in advance!
Marios C.

**Comment by andre-pdassis** [comment]
The command you provided is looking for a nonexistent schema.

You should use:

```
cake schema create tag --plugin Tags
```

You can find more informations in the database setup section on the [Docs](https://github.com/CakeDC/tags/blob/master/Docs/Documentation/Installation.md#database-setup).

**Comment by Megslalk** [comment]
Closing issue - Please re-open if you require further assistance!
