### ISSUE TITLE
actAs in AppModel will not work

### ISSUE THREAD

**Issue by mrahmadt** [CakeDC/tags#97]
For some reason if I include actAs inside AppModel it will not work with Tag plugin
every time it will try to create a tag it will fail

	var $actsAs = array('Tags.Taggable','Containable');

**Comment by dithmarschen77** [comment]
I got the same issue and get these error messages:

Error: Tags.TaggableBehavior could not be found.
Error: Create the class TaggableBehavior below in file: /var/www/html/mdm1/app/Plugin/Tags/Model/Behavior/TaggableBehavior.php

However, the file and class exists in the specified location.

**Comment by davidyell** [comment]
@dithmarschen77 Sounds like you've not loaded the plugin in your bootstrap
